### ISSUE TITLE
taxJar - Integration 

### ISSUE THREAD

**Issue by Thimothy01** [taxjar/taxjar-api-docs#23]
Hi,

I am asked to integrate  taxjar in our application, We have account in taxjar,

I need some guideline to start integrating Taxjar. Since we are not using either  Maven or Gradle.

So please help us to proceed further

Thanks
Thimothy

**Comment by fastdivision** [comment]
Hi @Thimothy01, if you're not using Maven or Gradle you can always download the JAR file here: http://repo1.maven.org/maven2/com/taxjar/taxjar-java/1.0.0/

If you have any other questions about getting started with our Java API client, please reach out to TaxJar support with your account email. Thank you!
